/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:40:14 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/CoreBrightness.framework/CoreBrightness
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_os_log;
#import <CoreBrightness-Structs.h>
@class NSObject;

@interface CBABCurve : NSObject {

	SCD_Struct_CB23 pref;
	float currentLux;
	float mappedBrightness;
	float _scaleFactor;
	unsigned long long _version;
}
@property (readonly) unsigned long long version;              //@synthesize version=_version - In the implementation block
@property (assign) float scaleFactor;                         //@synthesize scaleFactor=_scaleFactor - In the implementation block
-(id)initWithUUID:(id)arg1 ;
-(void)setScaleFactor:(float)arg1 ;
-(id)initWithConfiguration:(id)arg1 ;
-(id)init;
-(float)scaleFactor;
-(unsigned long long)version;
-(id)description;
-(BOOL)setLux:(float)arg1 ;
-(id)initWithUUID:(id)arg1 vendorID:(id)arg2 andProductID:(id)arg3 ;
-(void)setLinearBrightnessMin:(float)arg1 andMax:(float)arg2 ;
-(float)getLux;
-(float)getLinearBrightness;
-(float)getScaledBL1;
-(float)getScaledBL2;
-(void)setScaledBL1:(float)arg1 ;
-(void)setScaledBL2:(float)arg1 ;
-(void)updateALSParametersForDisplayBrightness:(float)arg1 ;
-(void)resetToDefaultState;
-(id)copyUserPrefState;
-(void)setSavedPrefences:(id)arg1 ;
@end