#import <shared.h>
/*
* This header is generated by classdump-dyld 1.0
* on Monday, March 13, 2023 at 1:40:14 AM Eastern European Standard Time
* Operating System: Version 16.3 (Build 20D47)
* Image Source: /System/Library/PrivateFrameworks/CoreBrightness.framework/CoreBrightness
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSObject;

typedef struct CustomCurve {
	float _E[20];
	float _L[20];
	int size;
} CustomCurve;

typedef struct _DisplayFactorFade {
	double period;
	double startTime;
	float Ftarget;
	float Fcurrent;
	float Fstart;
	float coeff[3];
} DisplayFactorFade;

typedef struct __IOMobileFramebuffer* IOMobileFramebufferRef;

typedef struct {
	unsigned sbim[3];
	unsigned long long duration_us;
} SCD_Struct_CB3;

typedef struct IOMFBShortTermBIM {
	unsigned version;
	SCD_Struct_CB3 v1;
} IOMFBShortTermBIM;

typedef struct MitigationState {
	int stage;
	BOOL violation;
	unsigned sbim_reset_frequency;
	unsigned sbim_timer_interval;
	unsigned mitigation_timer_interval;
	unsigned sbim_size;
	float delta_factor;
	float minutes_per_stop_mitigate;
	float minutes_per_stop_recovery;
	int sbim_above_max;
	int sbim_sustain_max;
	int sbim_above_num;
	int sbim_sustain_num;
	double lastStateUpdate_;
	unsigned sbim_read_stage;
	IOMFBShortTermBIM lastSBIMBlock_;
	float scalingFactor;
} MitigationState;

typedef struct __Display* DisplayRef;

typedef struct recoverycurve_t {
	float panelNits;
	float apce;
	unsigned long long size;
} recoverycurve_t;

typedef struct {
	unsigned field1;
	unsigned field2;
	unsigned long long field3;
	unsigned long long field4;
	unsigned long long field5;
	unsigned long long field6;
	unsigned field7;
	BOOL field8;
	BOOL field9;
	BOOL field10;
	float field11;
	float field12;
	float field13;
	unsigned long long field14;
} SCD_Struct_CB8;

typedef struct NMFactorState {
	double rampStartTime;
	float factor;
	float target;
	float start;
	float rampLength;
} NMFactorState;

typedef struct {
	int hour;
	int minute;
} SCD_Struct_Ni11;

typedef struct {
	SCD_Struct_Ni11 fromTime;
	SCD_Struct_Ni11 toTime;
} SCD_Struct_Ni12;

typedef struct {
	BOOL active;
	BOOL enabled;
	BOOL sunSchedulePermitted;
	int mode;
	SCD_Struct_Ni12 schedule;
	unsigned long long disableFlags;
	BOOL available;
} SCD_Struct_Ni13;

typedef struct __CFUserNotification* CFUserNotificationRef;

typedef struct {
	BOOL field1;
	BOOL field2;
	BOOL field3;
	int field4;
	SCD_Struct_Ni12 field5;
	unsigned long long field6;
	BOOL field7;
} SCD_Struct_Ni15;


typedef struct PeakAPCE {
	float current;
	float cap;
	float timeTaperConstant;
	float windowSize;
	float windowStart;
	NSObject<OS_dispatch_source>* recoveryTimer;
	float recoveryMultiplier;
	float recoveryWindowSize;
} PeakAPCE;

typedef struct RTPLCCapApplied {
	BOOL previous;
	float count;
	float triggerCount;
} RTPLCCapApplied;

typedef struct {
	float minCCT;
	float maxCCT;
	float midCCT;
} SCD_Struct_CB20;

typedef struct __IOHIDServiceClient* IOHIDServiceClientRef;

typedef struct __IOHIDEvent* IOHIDEventRef;

typedef struct {
	float minimumBrightness;
	float maximumBrightness;
	float bl1;
	float bl2;
	float e1;
	float e2;
	float eThresh;
} SCD_Struct_CB23;

typedef struct {
	float x;
	float y;
} SCD_Struct_CB24;

typedef struct {
	int orientation;
	float rawChannels[6];
	int nChannels;
	float brightness;
} SCD_Struct_CB25;

typedef struct {
	float XYZ[3];
	SCD_Struct_CB24 xy;
	float CCT1;
	SCD_Struct_CB25 extra;
} SCD_Struct_CB26;

typedef struct {
	unsigned status;
	unsigned char nChannels;
	unsigned char orientation;
	unsigned short brightness;
	unsigned integrationTime;
	unsigned reportInterval;
	int gain;
	float lux;
	float rawLux;
	float channelData[6];
	float CCT;
	short AZOffsets[6];
	float temperature;
	unsigned sensorTimestamp;
	int sensorType;
	unsigned short validNSamples;
	BOOL asyncMode;
	unsigned xtalkEstimate[6];
	BOOL colorCalcOnAOP;
	float XYZAP[3];
	float XYZAOP[3];
	float filteredLux;
	BOOL filteredLuxSet;
} SCD_Struct_CB27;

typedef struct {
	float field1[3];
	SCD_Struct_CB24 field2;
	float field3;
	SCD_Struct_CB25 field4;
} SCD_Struct_CB28;

typedef struct {
	BOOL blueReductionEnabled;
	BOOL blueReductionFactor;
	BOOL nightModeSupported;
	BOOL fadeInProgress;
	BOOL enforceSlowRamps;
	float brightnessBoost;
	BOOL whitePointEnabled;
	double enablementTs;
	BOOL forceSnapping;
	float currentChromaticitySensitivity;
	BOOL harmonySupported;
	BOOL harmonyEnabled;
	BOOL harmonyActive;
	BOOL harmonyAvailable;
	float harmonyStrength;
	float harmonyFixedStrength;
	BOOL presetDisableHarmony;
} SCD_Struct_CB29;

typedef struct {
	unsigned char firstTimerFire;
	NSObject<OS_dispatch_source>* logTimer;
	int periodS;
} SCD_Struct_CB30;

typedef struct {
	float field1;
	float field2[9];
	unsigned field3;
	float field4;
	SCD_Struct_CB24 field5;
	int field6;
	double field7;
} SCD_Struct_CB31;

typedef struct {
	BOOL field1;
	BOOL field2;
	BOOL field3;
	BOOL field4;
	float field5;
	BOOL field6;
	float field7;
	BOOL field8;
	float field9;
	BOOL field10;
	float field11;
	BOOL field12;
	float field13;
	BOOL field14;
	float field15;
	BOOL field16;
	float field17;
} SCD_Struct_CB32;


typedef struct __IOHIDEventSystemClient* IOHIDEventSystemClientRef;

typedef struct mach_timebase_info {
	unsigned numer;
	unsigned denom;
} mach_timebase_info;

typedef struct Ramp {
	float start;
	float target;
	float current;
	double startTime;
	double duration;
} Ramp;

typedef struct IONotificationPort* IONotificationPortRef;

typedef struct {
	unsigned ID;
	BOOL brightness_set;
	float brightness;
	BOOL whitepoint_set;
	float whitepoint[3][3];
	BOOL pccfactor_set;
	float pccfactor;
	BOOL brightnessLimit_set;
	float brightnessLimit;
	unsigned char reserved[5];
} SCD_Struct_CB40;

typedef struct {
	unsigned char version;
	unsigned sizeOfHeader;
	unsigned sizeOfEntry;
	unsigned numberOfUpdates;
	unsigned short frequency;
	float length;
	float ambient;
} SCD_Struct_CB41;

typedef struct ColorEffects* ColorEffectsRef;

typedef struct __IOHIDDevice* IOHIDDeviceRef;

typedef struct __IOHIDElement* IOHIDElementRef;

typedef struct {
	float targetMargin;
	BOOL rampInProgress;
	float targetScaler;
} SCD_Struct_CB45;

typedef struct {
	BOOL firstEvaluation;
	BOOL auroraStateSatisfied;
	BOOL displayStateSatisfied;
	BOOL luxSatisfied;
	BOOL autoBrightnessSatisfied;
	BOOL lowPowerModeSatisfied;
	BOOL gracePeriodSatisfied;
	BOOL aodStateSatisfied;
	BOOL cltmSatisfied;
	BOOL upoSatisfied;
} SCD_Struct_CB46;

typedef struct {
	float cltmCap;
	float upoCap;
	float activationThreshold;
	float entryDelta;
} SCD_Struct_CB47;

typedef struct {
	double field1;
	double field2;
} SCD_Struct_CB48;

typedef struct {
	double field1;
	double field2;
	double field3;
} SCD_Struct_CB49;

typedef struct APDSLuxInfo {
	float luxSamples;
	float gains;
	unsigned long long absoluteTime;
	char* coexFlags;
	int error;
	unsigned char numSamples;
} APDSLuxInfo;

typedef struct {
	double x;
	double y;
} SCD_Struct_CB51;

typedef struct {
	double X;
	double Y;
	double Z;
} SCD_Struct_CB52;

